version: '3.1'

services:
  app:
    image: nestjs-docker:local
    container_name: erp-backend-nestjs
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
